apiVersion: v1
kind: Secret
metadata:
  name: strategicai-secret
  namespace: strategicai
type: Opaque
# base64 encoded values
data:
  EIA_API_KEY: "" # base64 encoded
  FRED_API_KEY: "" # base64 encoded
  ANTHROPIC_API_KEY: "" # base64 encoded
  AZURE_OPENAI_API_KEY: "" # base64 encoded
  DATABRICKS_TOKEN: "" # base64 encoded
  ADMIN_PASSWORD: "" # base64 encoded
