apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-logs-dev-pvc
  namespace: strategicai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: collector-data-dev-pvc
  namespace: strategicai
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi # 개발용은 조금 더 작게 설정 가능
